# Generated by Django 4.2.29 on 2026-03-31 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Platz',
                'verbose_name_plural': 'Plätze',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('block_type', models.CharField(choices=[('training', 'Training'), ('match', 'Spieltag'), ('maintenance', 'Platzsperrung'), ('event', 'Veranstaltung')], max_length=20, verbose_name='Typ')),
                ('start_datetime', models.DateTimeField(verbose_name='Beginn')),
                ('end_datetime', models.DateTimeField(verbose_name='Ende')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('created_by', models.CharField(default='Verwaltung', max_length=100, verbose_name='Erstellt von')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courts.court', verbose_name='Platz')),
            ],
            options={
                'verbose_name': 'Sperrzeit',
                'verbose_name_plural': 'Sperrzeiten',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(max_length=100, verbose_name='Name')),
                ('booker_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('booker_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('start_datetime', models.DateTimeField(verbose_name='Beginn')),
                ('end_datetime', models.DateTimeField(verbose_name='Ende')),
                ('status', models.CharField(choices=[('confirmed', 'Bestätigt'), ('pending', 'Ausstehend'), ('cancelled', 'Storniert')], default='confirmed', max_length=20, verbose_name='Status')),
                ('cancellation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courts.court', verbose_name='Platz')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['start_datetime'],
            },
        ),
    ]
