# Generated by Django 4.2.30 on 2026-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='slot_duration_minutes',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Slot-Dauer (Minuten)'),
        ),
        migrations.AddField(
            model_name='court',
            name='slot_end_time',
            field=models.TimeField(default='20:00', verbose_name='Letzter Slot'),
        ),
        migrations.AddField(
            model_name='court',
            name='slot_start_time',
            field=models.TimeField(default='09:00', verbose_name='Erster Slot'),
        ),
        migrations.AddField(
            model_name='court',
            name='use_slots',
            field=models.BooleanField(default=False, verbose_name='Slot-Buchung aktiv'),
        ),
    ]
